### ISSUE TITLE
Application not responding to NC or fuzz scripts

### ISSUE THREAD

**Issue by dewest91** [justinsteven/dostackbufferoverflowgood#13]
Not sure if this is the right avenue to approach, but the application is not responding to netcat or fuzzing commands sent over from my kali machine. I've been using vulnserver.exe in the same VM that I'm running the dostackgood exe in, and that app had no issues for me. Any ideas as to what i could be missing?

**Comment by justinsteven** [comment]
I haven't heard of this before, sorry

Some things that might guide your troubleshooting:

* When you run the .exe does it start successfully and say "Listening for connections"?
* Use netstat or Process Explorer to check that the .exe is listening on 0.0.0.0:31337. If it's not, then... Something is very broken with the .exe or the VM you're running it on
* Run packet sniffers (e.g. Wireshark, tcpdump) on your attacker box and your Windows VM
  * When you send a SYN to dostackbufferoverflowgood.exe does it arrive at the Windows VM? If not, it's a networking issue on either end and/or between the hosts, or it could be a host-based firewall on the attacker box preventing the packet from being sent.
  * When the Windows VM gets the SYN, does it send a SYN/ACK back? If not, maybe it's a firewall on the Windows VM
* Try a different attacker box or Windows VM. Maybe play with your VM networking settings - try Bridged mode instead of NAT, or vice versa

Good luck, and feel free to report back if you find the issue. I can't help any further so I'll be closing this issue.
