### ISSUE TITLE
question about sub_esp_10

### ISSUE THREAD

**Issue by allthejunkfood** [justinsteven/dostackbufferoverflowgood#3]
In general is it OK to use sub_esp_10 or is that number best determined by the ESP?

**Comment by justinsteven** [comment]
In general I think it's fine. It depends on the implementation of GetPC more than anything. Shikata Ga Nai's GetPC requires a SUB ESP of at least 0d12 IIRC. I tend to use 0x10 (nice round number) and haven't had issues.

Metasploit modules tend to have a habit of using 3500! E.g. See https://github.com/rapid7/metasploit-framework/blob/master/modules/exploits/windows/smb/ms03_049_netapi.rb#L37

The value to sub from esp is largely habit and superstition rather than grounded in a truth I think 😉 not worth stressing about too much. Maybe one day you should dive in to the variety of GetPC routines, their inner workings, why they work that way, and come up with a sub esp value that will always work for you. In the meantime stick with 0x10 unless you get crashes that magically go away when you change it.

Cheers!

**Comment by allthejunkfood** [comment]
Awesome! Thank you so much for the info! 
Excellent Buffer Overflow tutorial as well. I've passed it along to some of my co workers.
